### ISSUE TITLE
Support for multiple coupons with specifc Keycloak group assignation

### ISSUE THREAD

**Issue by marcelovilla** [nebari-dev/nebari-self-registration#14]
**Is your feature request related to a problem? Please describe.**
Currently, all users are assigned to a single Keycloak group, despite of the coupon they use to register.

**Describe the solution you'd like**
It would be nice to be able to assign users to different groups, depending on the coupon they use to register. This way, permissions and access to different instance types can be easily controlled.

**Describe alternatives you've considered**
It was suggested before that the configuration could look like:
```yaml
coupons:
  - ANT:
    - account_expiration: 30
    - groups = [group1, group2]
    - approved_domains = [quansight.com, *.mil]
  - BAT:
    - account_expiration: 7
    - groups = [group3]
    - approved_domains = [*.mil]
 ```

**Additional context**
